### ISSUE TITLE
Rename operatorAddress to contractAddress 

### ISSUE THREAD

**Issue by guifel** [liquidity-network/invoice-generation#8]
It is the contract address that has to be specified, to operator address is something else.

**Comment by todorone** [comment]
Please review - #9
Is it right that if no `contractAddress` is mentioned, than it's an on-chain invoice?

**Comment by todorone** [comment]
@guifel Can You please answer on my last question?

**Comment by todorone** [comment]
Completed by https://github.com/liquidity-network/invoice-generation/commit/9bdc6a99062b7d6c973a83183a2eaad6ed078b24
